README.md
=> Examples section in readme

crates/chainio/clients/fireblocks/src/client.rs, crates/contracts/bindings/src/generate_bindings.rs, crates/crypto/bls/src/lib.rs
Since tests should be compiled only when running `cargo test`, this PR put the tests inside a `mod tests` module.
=> Test included inside mod tests block

Makefile
This PR adds an small change to the Makefile to reset the anvil container before running the tests (`pr` target in the makefile).
This makes the feedback loop shorter since devs don't need to manually remove the container between runs. 
Other possible improvements:
We can just call `docker stop anvil` or `docker start anvil` instead of calling the following scripts:
- ./crates/contracts/anvil/stop-anvil.sh
- ./crates/contracts/anvil/start-anvil.sh
=> reset anvil before running tests

Makefile, crates/contracts/anvil/start-anvil.sh, crates/contracts/anvil/stop-anvil.sh
This PR removes 2 scripts that were just calling single-line docker commands and replaces them with calls to the corresponding command.
It also makes the reset-anvil target run succesfully when there is no anvil container created.
=> Remove redundant scripts

.github/workflows/integration.yml, Makefile, README.md
- Updated coverage section of the README.
- Updated coverage target in Makefile to generate html report
=> Update coverage target and README

crates/chainio/clients/avsregistry/src/writer.rs, crates/services/bls_aggregation/src/bls_agg_test.rs, testing/testing-utils/src/anvil_constants.rs, testing/testing-utils/src/lib.rs, testing/testing-utils/src/transaction.rs
Small PR refactoring get_transaction_status function and fixing an unused import.
=> Refactor test utils

crates/chainio/clients/avsregistry/src/reader.rs
Restore `query_block_range` value back to 10000.
=> fix AvsRegistryReader test

crates/chainio/clients/elcontracts/src/writer.rs, crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs, examples/avsregistry-write/examples/register_operator_in_quorum_with_avs_registry_coordinator.rs, examples/info-operator-service/examples/get_operator_info.rs, testing/testing-utils/src/anvil_constants.rs
Added this rewards methods to ElContracts ChainWriter:
- `set_claimer_for`
- `process_claim`
Still missing this methods (they are still not merged on dev branch of eigenlayer-contracts - will be merged with the [slashing PR](https://github.com/Layr-Labs/eigenlayer-contracts/pull/679)):
- `ForceDeregisterFromOperatorSets`
- `SetOperatorCommissionBips`
=> Add Rewards methods

Cargo.lock, crates/chainio/clients/eth/Cargo.toml, crates/chainio/clients/eth/src/instrumented_client.rs, crates/chainio/txmanager/Cargo.toml, crates/chainio/txmanager/src/simple_tx_manager.rs, crates/signer/Cargo.toml, crates/signer/src/signer.rs, testing/testing-utils/src/anvil.rs
As foundry is no longer required, this PR updates some tests to run using an Anvil container.
Also, changed Anvil version on tests to `latest`. NOTE: this version works fine for AMD architectures but is not listed for ARM, so to run tests locally the image needs to be build manually, due to [this foundry issue](https://github.com/foundry-rs/foundry/issues/8039)
=> Fix TxManager, InstrumentedClient, Signer tests

README.md, crates/eigensdk/README.md
Existing command must have been from before some refactor? Thinking this what you need now:
```
cargo install eigen-cli --path crates/eigen-cli/
cargo install eigen-cli
```
=> Fix install instruction

Cargo.lock, crates/crypto/bls/Cargo.toml, crates/crypto/bls/src/lib.rs, crates/crypto/bn254/Cargo.toml, crates/crypto/bn254/src/utils.rs, crates/services/bls_aggregation/src/bls_agg.rs
This PR changes the signature of `sign_message` to:
``` rust
pub fn sign_message(&self, message: &[u8; 32]) -> Signature
```
and fixes the implementation of map_to_curve. There was a minor bug in the parsing of the input (endianness mismatch).
=> Fix BLS signature

Cargo.lock, Cargo.toml, crates/chainio/txmanager/Cargo.toml, crates/chainio/txmanager/src/simple_tx_manager.rs
Implement `send_tx_with_retries` to the Simple TxManager that sends a transaction and retries using Exponential Backoff
=> Add retries with exponential backoff to send transactions

crates/chainio/clients/avsregistry/src/writer.rs, crates/chainio/clients/elcontracts/src/lib.rs, crates/chainio/clients/elcontracts/src/reader.rs, crates/chainio/clients/elcontracts/src/writer.rs, crates/services/bls_aggregation/src/bls_agg_test.rs, crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs, examples/avsregistry-write/examples/register_operator_in_quorum_with_avs_registry_coordinator.rs, examples/info-operator-service/examples/get_operator_info.rs
This PR moves from the EL writer to the reader, these functions:
=> refactor: move read functions from `ELChainWriter` to `ELChainReader`

crates/chainio/clients/elcontracts/src/reader.rs, crates/chainio/clients/elcontracts/src/writer.rs
This PR adds functions:
- `GetOperatorAVSSplit`
- `GetOperatorPISplit`
- `SetOperatorAVSSplit`
- `SetOperatorPISplit`
=> feat: add get and set `split` functions

.github/workflows/integration.yml, README.md, crates/eigensdk/README.md
This PR includes the error message on the readme warning and fixes the command listed.
=> docs: add error message for `cargo test` on darwin

crates/chainio/clients/elcontracts/src/writer.rs
**Motivation**
The `test_register_and_update_operator` test fails since it tries to register an operator that is already registered.
This error was not caught before because it was using a wrong DelegationManager address and it was failing silently.
**Description**
This PR adds a new function `new_test_writer_with_private_key` that allows to create a test `ELChainWriter` with a specific account.
To fix the test, we simply use an unregistered account.
=> test: fix `test_register_and_update_operator  `

.github/PULL_REQUEST_TEMPLATE.md, .github/release.yml
This PR adds a GitHub release configuration, which should simplify changelog generation.
=> docs: add GitHub release changelog configuration

CHANGELOG.md
Fixes #
This PR fixes an oversight on the published changelog: a mention of the rewards-v2 changes updating the bindings.
=> docs: add mention of updated bindings to changelog

crates/contracts/script/DeployMockAvs.s.sol, crates/contracts/script/DeployMockAvsRegistries.s.sol, crates/contracts/script/DeployTokensStrategiesCreateQuorums.s.sol, crates/contracts/script/RegisterOperatorsWithEigenlayer.s.sol, crates/contracts/script/UpdateOperators.s.sol, crates/contracts/script/parsers/ConfigsReadWriter.sol, crates/contracts/script/parsers/EigenlayerContractsParser.sol, crates/contracts/script/parsers/MockAvsContractsParser.sol, crates/contracts/script/parsers/TokensAndStrategiesContractsParser.sol, crates/contracts/src/ContractsRegistry.sol, crates/contracts/src/MockAvsServiceManager.sol, crates/contracts/src/MockERC20.sol
Runs `forge fmt` to format the contracts in `crates/contracts`.
=> chore: format contracts

Makefile
This PR changes the `make bindings` target to remove the existing bindings before generating the new ones.
This is important since it removes potentially unused bindings.
=> chore: remove existing bindings when generating new ones

.github/workflows/changelog.yml, CHANGELOG.md
Fixes #238 
This PR adds a workflow that enforces the `CHANGELOG.md` file to be updated on every pull request.
It is also required that the changes in the changelog include the pull request URL.
**Important:** This check is skipped if the pull request includes the `changelog-ignore` label.
=> ci: add workflow to enforce updates to the changelog

Makefile, scripts/generate_bindings.sh
Fixes #
This PR moves the bindings generation logic to a script, to avoid having to install `make` in the docker image.
=> refactor: move bindings generation to script

CHANGELOG.md, crates/chainio/clients/fireblocks/src/contract_call.rs, testing/testing-utils/Cargo.toml
Fixes #
Removes hompage from testing utils. This used to throw error when deploying on crates io which i used to remove manually
=> remove homepage from testing-utils

.github/workflows/release-plz.yml, CHANGELOG.md, release-plz.toml
Fixes #
- release-plz will not generate changelog  . We will do it as we are doing right now i.e single changelog
- add a release-plz.toml for configuration to automatically do a github release.
-  only release when a PR is merged .
-  Exclude example packages
=> release-plz custom configuration

CHANGELOG.md, Cargo.toml, release-plz.toml
Fixes #
remove examples from workspace.dependencies and thereby remove mention in release-plz.toml
=> remove examples  from workspace.dependencies in Cargo.toml

.github/workflows/release-plz.yml, CHANGELOG.md
Fixes #
Removed release-plz-pr workflow in release-plz
=> Removed release-plz-pr workflow in release-plz

.github/workflows/integration.yml
Fixes #
Fireblocks tests don't work for external contributors. This PR splits the test run in the CI into two: "Run Tests" and "Generate Coverage". The idea is to have the first one run without fireblocks, while the second one runs with it and is not required for merge.
=> ci: split tests and coverage

CHANGELOG.md, crates/chainio/clients/avsregistry/src/writer.rs
Add new method `set_operator_set_param` to `avsregistry/writer`.
Related issue #310
=> feat: add new method `set_operator_set_param` in `avsregistry/writer`
